import type { Grammar } from "../core/types";

export const sql: Grammar = {
  name: "sql",
  aliases: ["mysql", "pgsql", "postgres", "postgresql", "sqlite", "plsql"],
  tokens: {
    comment: [
      { pattern: /--.*/, greedy: true },
      { pattern: /\/\*[\s\S]*?\*\//, greedy: true },
    ],
    string: [
      {
        pattern: /'(?:''|\\[\s\S]|[^\\'])*'/,
        greedy: true,
      },
      {
        pattern: /"(?:""|\\[\s\S]|[^\\"])*"/,
        greedy: true,
        alias: "identifier",
      },
    ],
    variable: [
      /@[@$]?\w+/,
      /:\w+/,
    ],
    keyword:
      /\b(?:ABORT|ABS|ABSOLUTE|ACCESS|ACTION|ADD|AFTER|AGGREGATE|ALL|ALLOCATE|ALTER|ANALYSE|ANALYZE|AND|ANY|ARE|ARRAY|AS|ASC|ASSERTION|AT|AUTHORIZATION|AVG|BACKWARD|BEGIN|BETWEEN|BIGINT|BINARY|BIT|BOOLEAN|BOTH|BY|CACHE|CALL|CASCADE|CASCADED|CASE|CAST|CATALOG|CHAIN|CHAR|CHARACTER|CHARACTERISTICS|CHECK|CHECKPOINT|CLASS|CLOSE|CLUSTER|COALESCE|COLLATE|COLLATION|COLUMN|COLUMNS|COMMENT|COMMIT|COMMITTED|CONCAT|CONDITION|CONFIGURATION|CONFLICT|CONNECT|CONNECTION|CONSTRAINT|CONSTRAINTS|CONTAINS|CONTINUE|CONVERSION|COPY|CORRESPONDING|COUNT|CREATE|CROSS|CSV|CUBE|CURRENT|CURRENT_CATALOG|CURRENT_DATE|CURRENT_ROLE|CURRENT_SCHEMA|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|CYCLE|DATA|DATABASE|DATE|DATETIME|DAY|DEALLOCATE|DEC|DECIMAL|DECLARE|DEFAULT|DEFAULTS|DEFERRABLE|DEFERRED|DELETE|DELIMITER|DELIMITERS|DENSE_RANK|DESC|DESCRIBE|DIAGNOSTICS|DISABLE|DISCARD|DISCONNECT|DISTINCT|DO|DOMAIN|DOUBLE|DROP|EACH|ELSE|ENABLE|ENCODING|END|ESCAPE|EVENT|EXCEPT|EXCEPTION|EXCLUDE|EXCLUDING|EXCLUSIVE|EXEC|EXECUTE|EXISTS|EXPLAIN|EXTENSION|EXTERNAL|EXTRACT|FALSE|FETCH|FILTER|FIRST|FLOAT|FOLLOWING|FOR|FORCE|FOREIGN|FORMAT|FORWARD|FOUND|FREE|FREEZE|FROM|FULL|FUNCTION|GENERATED|GET|GLOBAL|GO|GRANT|GRANTED|GROUP|GROUPING|GROUPS|HANDLER|HAVING|HEADER|HOLD|HOUR|IDENTITY|IF|ILIKE|IMMEDIATE|IMMUTABLE|IMPLICIT|IMPORT|IN|INCLUDING|INCREMENT|INDEX|INDEXES|INDICATOR|INHERIT|INHERITS|INITIALLY|INLINE|INNER|INOUT|INPUT|INSENSITIVE|INSERT|INSTEAD|INT|INTEGER|INTERSECT|INTERVAL|INTO|INVOKER|IS|ISNULL|ISOLATION|JOIN|JSON|KEY|LABEL|LANGUAGE|LARGE|LAST|LATERAL|LEAD|LEADING|LEFT|LEVEL|LIKE|LIMIT|LISTEN|LOAD|LOCAL|LOCALTIME|LOCALTIMESTAMP|LOCATION|LOCK|LOCKED|LOGGED|LOWER|MAPPING|MATCH|MATERIALIZED|MAX|MAXVALUE|MERGE|METHOD|MIN|MINUTE|MINVALUE|MOD|MODE|MONTH|MOVE|NAME|NAMES|NATIONAL|NATURAL|NCHAR|NEW|NEXT|NO|NONE|NOT|NOTHING|NOTIFY|NOTNULL|NOWAIT|NULL|NULLIF|NULLS|NUMERIC|OBJECT|OF|OFF|OFFSET|OIDS|OLD|ON|ONLY|OPEN|OPERATOR|OPTION|OPTIONS|OR|ORDER|ORDINALITY|OTHERS|OUT|OUTER|OUTPUT|OVER|OVERLAPS|OVERLAY|OVERRIDING|OWNED|OWNER|PARALLEL|PARAMETER|PARSER|PARTIAL|PARTITION|PASSING|PASSWORD|PLACING|PLAN|POLICY|POSITION|PRECEDING|PRECISION|PREPARE|PREPARED|PRESERVE|PRIMARY|PRIOR|PRIVILEGES|PROCEDURAL|PROCEDURE|PROGRAM|PUBLICATION|QUOTE|RANGE|RANK|READ|REAL|REASSIGN|RECHECK|RECURSIVE|REF|REFERENCES|REFERENCING|REFRESH|REINDEX|RELATIVE|RELEASE|RENAME|REPEATABLE|REPLACE|REPLICA|RESET|RESTART|RESTRICT|RETURN|RETURNING|RETURNS|REVOKE|RIGHT|ROLE|ROLLBACK|ROLLUP|ROUTINE|ROW|ROWS|ROW_NUMBER|RULE|SAVEPOINT|SCHEMA|SCHEMAS|SCROLL|SEARCH|SECOND|SECURITY|SELECT|SEQUENCE|SERIALIZABLE|SERVER|SESSION|SESSION_USER|SET|SETOF|SETS|SHARE|SHOW|SIMILAR|SIMPLE|SKIP|SMALLINT|SNAPSHOT|SOME|SQL|STABLE|STANDALONE|START|STATEMENT|STATISTICS|STDIN|STDOUT|STORAGE|STORED|STRICT|STRIP|SUBSCRIPTION|SUBSTRING|SUM|SYMMETRIC|SYSID|SYSTEM|TABLE|TABLES|TABLESAMPLE|TABLESPACE|TEMP|TEMPLATE|TEMPORARY|TEXT|THEN|TIES|TIME|TIMESTAMP|TO|TRAILING|TRANSACTION|TRANSFORM|TREAT|TRIGGER|TRIM|TRUE|TRUNCATE|TRUSTED|TYPE|TYPES|UESCAPE|UNBOUNDED|UNCOMMITTED|UNENCRYPTED|UNION|UNIQUE|UNKNOWN|UNLISTEN|UNLOGGED|UNTIL|UPDATE|UPPER|USAGE|USER|USING|VACUUM|VALID|VALIDATE|VALIDATOR|VALUE|VALUES|VARCHAR|VARIADIC|VARYING|VERBOSE|VERSION|VIEW|VIEWS|VOLATILE|WHEN|WHERE|WHITESPACE|WINDOW|WITH|WITHIN|WITHOUT|WORK|WRAPPER|WRITE|XML|XMLATTRIBUTES|XMLCONCAT|XMLELEMENT|XMLEXISTS|XMLFOREST|XMLNAMESPACES|XMLPARSE|XMLPI|XMLROOT|XMLSERIALIZE|XMLTABLE|YEAR|YES|ZONE)\b/i,
    builtin:
      /\b(?:ABS|AVG|CAST|CEIL|CEILING|COALESCE|CONCAT|COUNT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|DATE|DECODE|EXTRACT|FLOOR|FORMAT|GREATEST|IF|IFNULL|IIF|ISNULL|LEAD|LEAST|LEFT|LENGTH|LEN|LOG|LOG10|LOWER|LPAD|LTRIM|MAX|MIN|MOD|MONTH|NOW|NULLIF|NVL|OVER|PARTITION|POWER|REPLACE|REVERSE|RIGHT|ROUND|ROW_NUMBER|RPAD|RTRIM|SIGN|SPACE|SQRT|STR|STRING_AGG|STUFF|SUBSTR|SUBSTRING|SUM|SYSDATE|TRIM|TRUNC|TRUNCATE|UPPER|YEAR)\b/i,
    boolean: /\b(?:TRUE|FALSE)\b/i,
    number:
      /\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b/,
    operator:
      /[-+*/%]|!=|<>|<<|>>|<=|>=|<|>|=|&&|\|\||::|~|!|@@|\?\?|@>|<@|\?[|&]|#>>?|->>?|#-|&&|\|\|/,
    punctuation: /[{}[\]();,.]/,
  },
};
